### ISSUE TITLE
Question marks in comments get expanded

### ISSUE THREAD

**Issue by jliptrap** [Isti115/agda.nvim#2]
In an agda file with a line
```
-- why expand here?
```
Invoking `C-c C-l` (which by the way isn't documented in the readme) yields:
```
-- why expand here{!   !}
```

**Comment by isti115** [comment]
I've fixed the missing hotkey documentation and added a quick modification to the question mark replacement to only expand those that are either surrounded by spaces or line boundaries.  
Do you have any idea as to how question marks in comments could be most elegantly avoided? I have seen approaches that check the highlight group of the replacement candidates, but there didn't seem to be a clean way to do that and those resulted in rather messy solutions.

**Comment by jliptrap** [comment]
Thanks for the quick turnaround time!

Your fix works fine for the code I'm dealing with.  I'd naively imagine agda would know which question marks are holes; I'm not sure of a principled way for plugins to figure that out without parsing the code to figure out where the comments are, which should be agda's job.

**Comment by isti115** [comment]
Question marks are now expanded based on information from Agda since d7f20a1d16e5f1436024948da21b3271c54753a9, so this should no longer be an issue. (Previously it was just a hacky regex replacement...)
