### ISSUE TITLE
`vim.schedule` error when trying to load file  

### ISSUE THREAD

**Issue by iagoleal** [Isti115/agda.nvim#4]
Hi! I tried to load a simple Agda file to test interactive development:

```agda
data Nat : Set where
  zero : Nat
  suc : Nat → Nat

f : Nat → Nat
f x = ?
```
After pressing `<C-c><C-l>`, neovim reports the following error message:

    Error executing vim.schedule lua callback: ...m/site/pack/packer/start/agda.nvim/lua/agda/response.lua:20: attempt to index field 'constraintObj' (a number value)
    
Then the last line turns into `f x = {!   !}` where the `{!   !}` is not recognized as a goal by the other commands.

I'm on neovim 0.5.1, Agda 2.6.1 and this plugin's HEAD.

**Comment by iagoleal** [comment]
Oh, forgot to mention: I also inspected the code to see what 'constraintObj' was supposed to be.
So, at the time of the error, the decoded message is

```lua
{
  info = {
    errors = "",
    invisibleGoals = {},
    kind = "AllGoalsWarnings",
    visibleGoals = { {
        constraintObj = 0,
        kind = "OfType",
        type = "Nat"
      } },
    warnings = ""
  },
  kind = "DisplayInfo"
}
```

But on `response.lua`, line 20, the plugin is tried to access something like
`g.constraintObj.range[1].start.pos` where g runs over the elements of `message.info.visibleGoals`.
So... the message seems to only be sending the index of the contraint object. Is there any other place on the API where we can access the constraintObj through its index?

**Comment by isti115** [comment]
Sorry for the big delay this time and thanks for providing an example file that produces the error!
I will hopefully be able to look into this today!

**Comment by isti115** [comment]
Hmm, I have tried to test this and cannot reproduce the error so far. :thinking:
(The only difference being Agda 2.6.2 on my system.)
@jliptrap Could you please try this as well?

**Comment by iagoleal** [comment]
Apparently the problem was really the Agda version.
I just updated to v2.6.2 and loading works as expected! :D 
Now that we know this, I think that it may also be worth to have a notice somewhere about Agda version compatibility.
