### ISSUE TITLE
Vim-friendly default mappings?

### ISSUE THREAD

**Issue by jliptrap** [Isti115/agda.nvim#5]
Commands like `<C-c><C-l>` are ergonomic for emacs, but `C-c` is already a vim command, and CTRL-heavy mappings aren't ergonomic by vim standards.  Might it be worth changing the default mappings to `<leader>cl` etc., to fit vim conventions while still clearly corresponding to agda commands in emacs or vscode?  [CamelCaseMotion](https://github.com/bkad/CamelCaseMotion) seems like a good example of this style.

**Comment by isti115** [comment]
Personally I don't use Ctrl based mappings at all, but I included them to make moving over from Emacs as little effort as possible, but I will definitely provide some other options as well later on. I was thinking about using `<LocalLeader>l` for load and so on.

**Comment by isti115** [comment]
I've created an option for setting a preferred keymap style, please test it if you can! :keyboard:

**Comment by jliptrap** [comment]
I like this approach, both vim and emacs styles work.  Thanks!
