### ISSUE TITLE
[Feature Request] Need Shortcut Key `C-c C-d`

### ISSUE THREAD

**Issue by kands-code** [Isti115/agda.nvim#7]
I am a newbie to Agda, because I am not used to Emacs, so I choose to use Neovim to learn Agda.

In the process of learning Agda, I found a shortcut key `C-c C-d`, "one can get agda to type check a given expression", but I didn't find the corresponding shortcut key in [here](https://github.com/Isti115/agda.nvim/blob/main/ftplugin/agda.vim)

Is there any way to use the corresponding function? Or is there a corresponding shortcut key?

**Comment by isti115** [comment]
Thanks for the feedback, I will make sure to include this action in the next version!
(Currently I'm waiting on this issue: https://github.com/agda/agda/issues/5665 to be addressed, but in the meantime I might switch to the Lisp backend, which could be a bit painful, but at least would enable the further development of this plugin...)

**Comment by isti115** [comment]
Sorry for such a big delay, I have kind of given up on waiting for the fix of the interaction bug mentioned above, so I will continue implementing features and hope that it will be addressed at some point later. If all goes well I should be able to add type inference and normal form computation in the following few days, but I have also realized that while this is missing, you can just simply create an empty goal (`test =  ?`), load the file, enter whatever you'd like to check the type of into it and use `C-c C-.` to see the inferred result in the `Have:` section.

**Comment by kands-code** [comment]
Thank you!

**Comment by isti115** [comment]
@kands-code This has now been properly added in dd96cb75ecb2ae4f21c9cffa1bdc96533f474207, can you test it please?

If your cursor is within a goal, it should use the context of that goal and also try to use the content of the goal first. In case the content is empty, it should ask for an expression, and if you are outside of a goal, it should ask for an expression right away and pass it with the top level context.

**Comment by kands-code** [comment]
I tried it, the experience is very good, it can be used normally, thank you very much
